# Generated by Django 4.1.3 on 2022-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=9)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
    ]
