# Generated by Django 4.1.3 on 2022-11-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_validid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
    ]
