# Generated by Django 4.1.3 on 2022-11-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name', 'category', 'brand', 'price', 'unit', 'qty', 'created_by')},
        ),
    ]
