# Generated by Django 4.1.3 on 2022-11-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0004_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('product_name', 'brand', 'price', 'unit', 'qty', 'user'),
            },
        ),
    ]
