# Generated by Django 4.1.3 on 2022-11-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0005_returnedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=30)),
                ('spending', models.CharField(max_length=30)),
            ],
        ),
    ]
