# Generated by Django 4.1.3 on 2022-11-29 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0006_money'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'ordering': ('budget', 'spending')},
        ),
    ]
