# Generated by Django 4.1.3 on 2022-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0008_rename_money_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('to', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=30)),
                ('start_of_loan', models.DateField()),
                ('end_of_loan', models.DateField()),
            ],
            options={
                'ordering': ('product_name', 'category', 'brand', 'to', 'status', 'start_of_loan', 'end_of_loan'),
            },
        ),
    ]
