# Generated by Django 4.1.3 on 2022-12-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0009_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
