# Generated by Django 4.1.3 on 2022-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0010_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Loaned', 'Loaned')], max_length=200),
        ),
    ]
