# Generated by Django 4.1.3 on 2022-12-10 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0013_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name', 'category', 'brand', 'price', 'unit', 'qty', 'created_by', 'adding_date')},
        ),
        migrations.AddField(
            model_name='product',
            name='adding_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
